# Generated by Django 5.0.14 on 2026-06-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('action_type', models.CharField(choices=[('view', 'View'), ('add_to_cart', 'Add to Cart'), ('purchase', 'Purchase'), ('rate', 'Rate'), ('search', 'Search')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_user_behaviors',
            },
        ),
    ]
