from django.contrib import admin
from django.urls import path
from gateway_app import views

urlpatterns = [
    path('', views.index_view, name='gateway_ui'),
    path('admin/', admin.site.urls),
    path('api/gateway/customers', views.customer_list_view, name='customer_list'),
    path('api/gateway/customers/<int:customer_id>', views.customer_detail_view, name='customer_detail'),
    path('ui/api/status', views.ui_status_view, name='ui_status'),
    path('ui/api/login', views.ui_login_view, name='ui_login'),
    path('ui/api/products', views.ui_products_view, name='ui_products'),
    path('ui/api/addresses', views.ui_addresses_view, name='ui_addresses'),
    path('ui/api/cart', views.ui_cart_view, name='ui_cart'),
    path('ui/api/cart/items', views.ui_cart_items_view, name='ui_cart_items'),
    path('ui/api/cart/items/<int:product_id>', views.ui_cart_items_view, name='ui_cart_item_detail'),
    path('ui/api/cart/checkout-preview', views.ui_checkout_preview_view, name='ui_checkout_preview'),
    path('ui/api/orders', views.ui_orders_view, name='ui_orders'),
    path('ui/api/orders/<int:order_id>', views.ui_order_detail_view, name='ui_order_detail'),
    path('ui/api/payments', views.ui_payments_view, name='ui_payments'),
    path('ui/api/payments/<int:payment_id>/confirm', views.ui_payment_confirm_view, name='ui_payment_confirm'),
    path('ui/api/shipments/order/<int:order_id>', views.ui_shipment_by_order_view, name='ui_shipment_by_order'),
    path('ui/api/shipments/<int:shipment_id>', views.ui_shipment_update_view, name='ui_shipment_update'),
    path('ui/api/behaviors', views.ui_behaviors_view, name='ui_behaviors'),
    path('ui/api/admin/users', views.ui_admin_users_view, name='ui_admin_users'),
    path('ui/api/admin/users/<int:target_user_id>', views.ui_admin_user_detail_view, name='ui_admin_user_detail'),
    path('ui/api/admin/products', views.ui_admin_products_view, name='ui_admin_products'),
    path('ui/api/admin/products/<int:product_id>', views.ui_admin_products_view, name='ui_admin_product_detail'),
    path('ui/api/admin/categories', views.ui_admin_categories_view, name='ui_admin_categories'),
    path('ui/api/admin/orders', views.ui_admin_orders_view, name='ui_admin_orders'),
    path('ui/api/admin/orders/<int:order_id>', views.ui_admin_orders_view, name='ui_admin_order_detail'),
    path('ui/api/admin/orders/<int:order_id>/<str:action>', views.ui_admin_orders_view, name='ui_admin_order_action'),
    path('ui/api/staff/orders', views.ui_staff_orders_view, name='ui_staff_orders'),
    path('ui/api/staff/orders/<int:order_id>/<str:action>', views.ui_staff_orders_view, name='ui_staff_order_action'),
    path('ui/api/admin/payments', views.ui_admin_payments_view, name='ui_admin_payments'),
    path('ui/api/admin/payments/<int:payment_id>', views.ui_admin_payments_view, name='ui_admin_payment_detail'),
    path('ui/api/admin/shipments', views.ui_admin_shipments_view, name='ui_admin_shipments'),
    path('ui/api/admin/shipments/<int:shipment_id>/<str:action>', views.ui_admin_shipments_view, name='ui_admin_shipment_action'),
    path('ui/api/shipper/shipments', views.ui_shipper_shipments_view, name='ui_shipper_shipments'),
    path('ui/api/shipper/shipments/<int:shipment_id>/<str:action>', views.ui_shipper_shipments_view, name='ui_shipper_shipment_action'),
]
