# Generated by Django 5.0.14 on 2026-06-12 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product_app.product')),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=50, unique=True)),
                ('page', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'books',
            },
            bases=('product_app.product',),
        ),
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product_app.product')),
                ('brand', models.CharField(max_length=100)),
                ('skin_type', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('origin', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cosmetics',
            },
            bases=('product_app.product',),
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product_app.product')),
                ('brand', models.CharField(max_length=100)),
                ('warranty', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'electronics',
            },
            bases=('product_app.product',),
        ),
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product_app.product')),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'fashion',
            },
            bases=('product_app.product',),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product_app.product')),
                ('brand', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('origin', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'food',
            },
            bases=('product_app.product',),
        ),
        migrations.CreateModel(
            name='HealthCare',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product_app.product')),
                ('brand', models.CharField(max_length=100)),
                ('ingredient', models.TextField()),
                ('expiry_date', models.DateField()),
                ('usage', models.TextField()),
            ],
            options={
                'db_table': 'health_care',
            },
            bases=('product_app.product',),
        ),
        migrations.CreateModel(
            name='HomeKitchen',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product_app.product')),
                ('brand', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=50)),
                ('warranty', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'home_kitchen',
            },
            bases=('product_app.product',),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product_app.product')),
                ('brand', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'office',
            },
            bases=('product_app.product',),
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product_app.product')),
                ('brand', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('sport_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sports',
            },
            bases=('product_app.product',),
        ),
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product_app.product')),
                ('brand', models.CharField(max_length=100)),
                ('age_range', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=100)),
                ('player_count', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'toys',
            },
            bases=('product_app.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_app.category'),
        ),
    ]
